---

- name: Generate VPC template
  template: src="vpc.json.j2" dest="{{ tmp_dir }}/vpc.json"

- name: Create VPC
  cloudformation:
    stack_name: "{{ stack }}-network"
    state: "present"
    region: "{{ aws_region }}"
    disable_rollback: true
    template: "{{ tmp_dir }}/vpc.json"
    tags:
      stack: "{{ stack }}"
  register: network_aws_stack

- name: Show stack outputs
  debug: msg="My stack outputs are {{network_aws_stack.stack_outputs}}"

- name: Define Outputs
  set_fact:
    network_aws: "{{ {'output': {'network_id': network_aws_stack.stack_outputs.vpc}} }}"
